### ISSUE TITLE
How to use v-html

### ISSUE THREAD

**Issue by fabianmu** [AlbertLucianto/vue-text-highlight#1]
I have a `.vue` file with the following code:
```
<section v-html="page.parsed_content"></section>
```
which, obviously, renders `page.parsed_content` as raw HTML within the `section` tag.  
Now I'd like to add highlights but don't know how to mix/use `v-html` with the `description` used in `vue-text-highlight`
```
<section>
  <text-highlight :queries="testhighlight" v-html="page.parsed_content"></text-highlight>
</section>
```
does not work, I'm new to vue and I guess I am missing something very simple, any idea?
Thanks!

**Comment by AlbertLucianto** [comment]
Hi @fabianmu, `v-html` attribute is not listed in the api and won't affect anything. Currently, vue-text-highlight only accepts plain string as its default slot or children.

Supporting `v-html` directive will add unwarranted complexity which is out of this library's scope. Also, I don't encourage using `v-html` thus I tried to avoid this in the implementation.

Closing this. Feel free to reopen or create a PR related to this.

**Comment by hqzh** [comment]
[解决方案](https://zhuanlan.zhihu.com/p/133950569)
