### ISSUE TITLE
vue-text-highlight 2.0.5 fails to resolve

### ISSUE THREAD

**Issue by ruifigueira** [AlbertLucianto/vue-text-highlight#11]
Hi,

I upgraded to 2.0.5 and start getting the following error:

```
This dependency was not found:

vue-text-highlight in ./src/globalComponents.js

To install it, you can run: npm install --save vue-text-highlight
```

With 2.0.2 it worked, and I noticed that in this latest version, `dist` folder is missing.

**Comment by AlbertLucianto** [comment]
Please try upgrading to v2.0.6.

Both v2.0.4 and v2.0.5 are broken build due to some changing behaviour in npm.
