### ISSUE TITLE
Can you please provide a sample of using highlightComponent with typescript class component?

### ISSUE THREAD

**Issue by ramgesg** [AlbertLucianto/vue-text-highlight#16]
Getting this error. [Vue warn]: Invalid prop: type check failed for prop "highlightComponent". Expected String, Object, got Function 

found in

---> <TextHighlight>

My CustomComponent.vue looks like this:
`<template>
  <mark class="custom">
    <slot></slot>
  </mark>
</template>`

`<script lang="ts">
import { Component, Vue, Prop } from 'vue-property-decorator'
@Component({
  name: 'EntityPop'
})
export default class extends Vue {
  //@Prop({ required: true }) private visible!: boolean
  @Prop({ required: true }) private index!: number
  @Prop({ required: true }) private text!: string
}
</script>`

**Comment by lifenautjoe** [comment]
How did you fix this @ramgesg ?
