### ISSUE TITLE
Is there a way to remove text__highlight class all togather?

### ISSUE THREAD

**Issue by geongeorge** [AlbertLucianto/vue-text-highlight#17]
Hey,
I noticed I was not able to change the styles even after binding classes.
The text__highlight class is overriding every other classes(tailwind) I add.
I do not wanna use !important, is there any other solution?
```html
<text-highlight 
      :queries="queries"
      :highlightClass="['bg-red-200', 'rounded']"
      >
```
![image](https://user-images.githubusercontent.com/29296982/62668948-5c43bc80-b9ab-11e9-981b-143c0dfce36a.png)

Regards,
Geon George

**Comment by taeyeon-Kim** [comment]
t

**Comment by zefexdeveloper** [comment]
I had the same issue using Tailwind, it's impossible to change the default color because `text__highlight` is overwriting it.

**Comment by AlbertLucianto** [comment]
Hi @geongeorge, @zefexdeveloper, thanks for raising the issue!

In v2.0.10, you can do

```js
import TextHighlighter from 'vue-text-highlight/dist/component';
import 'vue-text-highlight/dist/style.css';
```

Hope that solves your issue! 😄
