### ISSUE TITLE
How does it works with vue directives  v-html ? 

### ISSUE THREAD

**Issue by tasamphel** [AlbertLucianto/vue-text-highlight#19]
How does this component works with vue directives "v-html" instead of vue text interpolation using  “Mustache”. for example - currently in your example it's written
`<text-highlight :queries="queries">{{ description }}</text-highlight>`
 If I want to use it like this --
`<text-highlight :queries="queries"><span v-html="rawHtml"></span></text-highlight> `
OR
`<text-highlight :queries="queries" v-html="rawHtml"></text-highlight>`

**Comment by AlbertLucianto** [comment]
Duplicates #1

**Comment by hqzh** [comment]
[解决方案](https://zhuanlan.zhihu.com/p/133950569)
