### ISSUE TITLE
Multiple hightlight

### ISSUE THREAD

**Issue by komxvl** [AlbertLucianto/vue-text-highlight#27]
If I type in search input two words, nothing happens. What I need to do for hightlight two words?!

**Comment by AlbertLucianto** [comment]
`text-highlight` component accepts `Array<string>` for `queries` prop. You can try splitting your search input.

**Comment by komxvl** [comment]
[Work great](https://codesandbox.io/live/qz4jk?fbclid=IwAR2qnnKn7EvOatMDwGf-prGozjwhbOBHCuPNi6-mWqUp27rgwJzzQqrUhRo)! Thnk!
