### ISSUE TITLE
Demo is broken!

### ISSUE THREAD

**Issue by samtstern** [AlbertLucianto/vue-text-highlight#47]
At the moment this link from the README 404s:
https://albertlucianto.github.io/vue-text-highlight

<img width="1010" alt="Screen Shot 2021-04-01 at 3 38 19 PM" src="https://user-images.githubusercontent.com/8466666/113310576-64661380-92d6-11eb-9955-d869607aae07.png">

**Comment by AlbertLucianto** [comment]
Hi @samtstern, thanks for reporting! It's fixed now.
