### ISSUE TITLE
Events when click on the highlighted word

### ISSUE THREAD

**Issue by calebeaires** [AlbertLucianto/vue-text-highlight#7]
Would be useful If an event is triggered when the user clicks on a highlighted word.

**Comment by AlbertLucianto** [comment]
I'm planning to provide a prop for custom component for the highlighted word. In that case, that component may include handling for user clicks.

**Comment by AlbertLucianto** [comment]
@calebeaires now custom component is supported in v2. Hope this can suit your requirements.
